### ISSUE TITLE
stops working when used in conjunction with other touch buttons

### ISSUE THREAD

**Issue by furroy** [shinneider/godot_touchJoyPad#1]
Worked great at first until I added some other touch buttons in my UI to attack. Then whenever the other buttons are pressed, it stops tracking the analog stick. You have to release the joystick and press on it again which is a deal breaker.

**Comment by furroy** [comment]
So I made way too many changes to this codebase for my project, but if anyone else gets tripped up on this,  I think the critical change is in extractPointerIdx()  if touch or drag: return event.index 
Instead of return 1

**Comment by furroy** [comment]
there was another visual issue where touching the other buttons made the analog ball flash if you can figure that one out

**Comment by shinneider** [comment]
I need a help to evaluate the opened pr.
in the last months i involved in some projects, and no have time to configure a environment and simulate this error.
so if you have time, evaluate and tape the result here, if all is ok, i merge into master

**Comment by shinneider** [comment]
@furroy @odbol
